### ISSUE TITLE
allow multiple concurrent debugging connections / sessions

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-reactor#100]
This is a follow up of this issue: https://github.com/elm-lang/elm-reactor/issues/97

It would be nice to be able to be able to service multiple targets from elm-reactor. This is very common in web development as you want to see how things look and feel on multiple browsers (including mobile). 

I think it is interesting to discuss how this feature will look like. For example, do we want the exact same state to be reflected on all browsers? Do we want each instance to be completely independent? Should this be some sort of flag/option?

**Comment by evancz** [comment]
Tracking in #193, follow along there!
