### ISSUE TITLE
Error messages should be HTML-escaped

### ISSUE THREAD

**Issue by nathan** [elm-lang/elm-reactor#101]
When I run elm-reactor from an project I made using the Elm 0.14 tools, I get the following error message:

```
Error reading file elm-stuff/packages/elm-lang/core/1.1.1/elm-package.json:
   Missing field "elm-version", acceptable versions of the Elm Platform (e.g. "0.15.0 <= v < 0.16.0").
   Check out an example elm-package.json file here:
   
```

(Note the missing URL.) Running `elm-package install` from the command line reveals the correct error message:

```
$ elm-package install

Error: Error reading file elm-package.json:
    Missing field "elm-version", acceptable versions of the Elm Platform (e.g. "0.15.0 <= v < 0.16.0").
    Check out an example elm-package.json file here:
    <https://raw.githubusercontent.com/evancz/elm-html/master/elm-package.json>
```

It looks like [Compile.hs:71](https://github.com/elm-lang/elm-reactor/blob/ec35c68d075cf1a6712cd3c01fc343deb6b897bd/backend/Compile.hs#L71) should be using [`toMarkup`](http://hackage.haskell.org/package/blaze-markup-0.7.0.2/docs/Text-Blaze.html#v:toMarkup) instead of [`preEscapedToMarkup`](http://hackage.haskell.org/package/blaze-markup-0.7.0.2/docs/Text-Blaze.html#v:preEscapedToMarkup), but I'm not sure if other error messages rely on the current (HTML-enabled) behavior.

**Comment by evancz** [comment]
Do you mind sending a PR? The error messages are taken directly from the command line messages, so there should be no HTML in there.

**Comment by nathan** [comment]
Sure. Here's the PR: https://github.com/elm-lang/elm-reactor/pull/102.
