### ISSUE TITLE
WIP: convert JS to Elm

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-reactor#106]
There are two parts to this, the UI and the time travel logic.

### UI

General goal is to move as many layers of UI into Elm as possible. In the end, I'd hope the only thing left in JS is the UI for the users Elm app.

  * [x] Use sliders from elm-html, not a custom native library
  * [x] Move logic for toggling the sidebar and event blocker into Elm
  * [ ] Display errors with Elm, not with crazy JS

### Time Travel Logic

There are a couple key pieces of information that elm-reactor tracks:

  * All events that have occurred (ID, time, value)
  * A record of all "watches" so we can scrub through them
  * A record of all "traces" so we can draw them on top of 
  * The current position in time (playing or paused at a certain time)

Doing this all in JS is awful. It's easy to forget to update things or to update things accidentally. If we can figure out how to do it all in Elm, I think the code would be much easier to maintain. Even if we only have a plan to do it, I think that could improve the existing JS code.

I bring this up because it seemed to fit with the UI changes when I started exploring this general direction.

**Comment by vilterp** [comment]
It seems that the code for swapping the new functions into the signal graph and transferring the state from the old SG to the new (i.e. [`transferState` and `swap`](https://github.com/elm-lang/elm-reactor/blob/4212d85c3d9f9cf75b19f437a7402352f096e455/frontend/debugger-implementation.js#L417-L474)) will have to remain in JS as well (?)

**Comment by vilterp** [comment]
Overhaul design doc: https://gist.github.com/vilterp/befbf20eb67d8c3b74ec
