### ISSUE TITLE
Setup.hs call to elm-make can fail when elm-reactor is built by Nix

### ISSUE THREAD

**Issue by andremarianiello** [elm-lang/elm-reactor#109]
When installing elm-reactor with Nix, the action buildSideBar in Setup.hs will fail if the user's $HOME variable is set /homeless-shelter, as is the case when Nix builds it. This is because Setup.hs runs elm-make, and elm-make uses elm-package, which by default uses System.Directory.getUserAppDataDirectory as the path for the build cache. elm-make tries to create the build cache folder, but to do that it has to create the /homeless-shelter folder. This fails because the Nix builder user account doesn't have the right permissions, so the directory creation fails. This causes the elm-make run to fail. This causes Setup.hs to fail. This causes the entire build process for elm-reactor to fail.

The work-around I am using is to chance $HOME to be equal to $TMPDIR in Setup.hs before running elm-make, but there might be a better solution.

**Comment by jvoigtlaender** [comment]
@andremarianiello, is the situation still as you described above? If so, can you move this issue over to the https://github.com/elm-lang/elm-platform repository? That's where build-from-source issues are dealt with.

**Comment by andremarianiello** [comment]
I haven't used Nix or Elm in months. I have no idea if this is still the case. Someone could easily check if they already have a box running Nix. I no longer have one.

**Comment by evancz** [comment]
Not sure how to act on the initial situation so going to close.
