### ISSUE TITLE
elm-reactor 0.15.1 Build from source fails.

### ISSUE THREAD

**Issue by garyLockyer** [elm-lang/elm-reactor#116]
Get the following for elm-reactor (all other items build ok)
Resolving dependencies...
In order, the following would be installed:
SHA-1.6.4.2 (new package)
bytestring-mmap-0.2.2 (new package)
entropy-0.3.7 (new package)
enumerator-0.4.20 (new package)
attoparsec-enumerator-0.3.4 (new package)
blaze-builder-enumerator-0.2.1.0 -newbuilder (new package)
hinotify-0.3.7 (new package)
monads-tf-0.1.0.2 (reinstall) changes: transformers-0.3.0.0 -> 0.4.3.0
MonadCatchIO-transformers-0.3.1.3 (new version)
regex-base-0.93.2 (reinstall) changes: mtl-2.1.2 -> 2.2.1
regex-posix-0.95.2 (reinstall)
system-filepath-0.4.13.4 (new package)
system-fileio-0.3.16.3 (new package)
fsnotify-0.1.0.3 (new package)
unix-compat-0.4.1.4 (new package)
websockets-0.9.5.0 (new package)
zlib-bindings-0.1.1.5 (new package)
zlib-enum-0.2.3.1 (new package)
snap-core-0.9.7.0 (new package)
snap-server-0.9.5.1 (new package)
websockets-snap-0.9.2.0 (new package)
elm-reactor-0.3.2 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
MonadCatchIO-transformers-0.3.1.0
MonadCatchIO-mtl-0.3.1.0
cgi-3001.1.8.5
regex-compat-0.95.1
Use --force-reinstalls if you want to install anyway

**Comment by evancz** [comment]
Yes, I see this too on certain platforms. What OS are you using?

I have not been able to figure out the root cause though, I suspect we need to add constraints to *something*. Can you try to figure out which projects are requiring MonadCachIO?

**Comment by garyLockyer** [comment]
Ubuntu 15.04

I'll take a look and see what I can work out,

**Comment by garyLockyer** [comment]
Looks to be the versions of transformers and mtl installed on ubuntu
The following enables a successful build:
sudo ghc-pkg --force unregister transformers
sudo ghc-pkg --force unregister mtl

But I'm not sure what harm that does to the underlying ghc install and ubuntu packages.

**Comment by garyLockyer** [comment]
It looks like it's an issue with the haskell-platform package.  Un-installing it and installing just the ghc package fixes the problem, with the added advantage of having no broken packages.

Let me know if I can do anything more

**Comment by evancz** [comment]
Hmm, it may make sense to add the [fubar.sh](https://www.reddit.com/r/elm/comments/34np4m/how_to_uninstall_elm/) script to the build from source process. I find that the best way to get haskell running is to get ghc and cabal and then trash everything else.

**Comment by garyLockyer** [comment]
I not sure that it should be included in the process by default.  My reservation is that while fixing the elm build it could trash other Haskell builds.  Or am I worrying about nothing.

So maybe as an option to run if there are broken packages.

**Comment by evancz** [comment]
Oh, definitely! If you have other stuff done in Haskell it could be bad. Good point!
