### ISSUE TITLE
First time impressions

### ISSUE THREAD

**Issue by maxhoffmann** [elm-lang/elm-reactor#117]
This is my first time trying the Elm language and its tooling, so I wanted to give you some impressions of playing around with `elm-reactor`. My background is JS with React and webpack using `react-hot-loader`, so hot reloading was not a new concept to me. I’m using latest OS X Yosemite, Sublime Text and latest Chrome. First of all installation and documentation was easy. :+1: 

When I started testing `elm-reactor` with `elm-architecture-tutorial` and `elm-examples` I stumbled across some first obstacles though.

- **hot swapping**
  - is unreliable
  - most often there are no errors in the console if it doesn’t work
  - updating `elm-architecture-tutorial/4/Counter.elm` does not get swapped and breaks events
  - sometimes it works, but events don’t trigger anymore
  - sometimes I get these errors:
    - `WebSocket connection to 'ws://localhost:8000/socket?file=Counter.elm' failed: Could not decode a text frame as UTF-8.`
    - `Uncaught Error: Assertion error: number of watch frames (1) should match current index (0)`
    - `Uncaught Error: The notify function has been called synchronously!
This can lead to frames being dropped.
Definitely report this to <https://github.com/elm-lang/Elm/issues>`
- **restart button**
  - I am not sure what it is supposed to do
  - it always throws this error for me: `Uncaught TypeError: Cannot read property 'time' of undefined`
- **the “time travel” slider**
  - works in most cases
  - the knob moves slower than the mouse for events > 200 in the mario example
  - moving the knob disables events (like clicking a button) This was surprising to me although it switches to pause mode. I expected it to override the rewinded events. Maybe it could show a small hint somewhere?
- **`elm-reactor`**
  - does only work if the elm file with the `main` function is in the root directory, e.g. running `elm-reactor` inside of `elm-architecture-tutorial` did not work

Most important questions for me:
- What should the restart button do?
- Can dependencies of an Elm file be hot swapped?

Hope this feedback helps you to improve the onboarding experience. :)

**Comment by maxhoffmann** [comment]
seems like some of these issues are or will be adressed here: https://github.com/elm-lang/elm-reactor/issues/106

**Comment by vilterp** [comment]
Thanks for the helpful summary! I will be focusing on the reactor fulltime as an intern for the next ~2 months and will be trying to address as many of these issues as possible, starting with all these JS runtime errors and swapping being unreliable.

- Restart button is supposed to reset the program to its original state, discarding all user input events.
- Not sure if this is what you're asking, but the reactor does watch all files which the file you are viewing depends on (in your source tree; not across libraries), and will trigger a swap if any of them changes.

**Comment by maxhoffmann** [comment]
Thanks for the clarification. Unfortunately watching dependencies is buggy for me as well. Will try to help fixing bugs as soon as I have enough experience with the language itself. Great to see progress.

**Comment by netaisllc** [comment]
@maxhoffmann 
> it always throws this error for me: Uncaught TypeError: Cannot read property 'time' of undefined

For me as well.
And I don't think the debugger is as easy to understand as others may.  It presupposes knowledge of Elm that I don't yet have.  A start: tool tips.
