### ISSUE TITLE
runtime error when restart button pressed

### ISSUE THREAD

**Issue by vilterp** [elm-lang/elm-reactor#122]
Pressing the restart button immediately results in this JS error:

![screen shot 2015-07-13 at 1 26 27 pm](https://cloud.githubusercontent.com/assets/7341/8659930/d0e435ca-2962-11e5-8c36-f0200f147011.png)

```
(Uncaught TypeError: Cannot read property 'time' of undefined
```

Using Elm 0.15.1

**Comment by vilterp** [comment]
Happening because we're trying to get the 0th event in `runtime.timer.now`, but there are no events because we just cleared them all. Need to get the time from some other source.

**Comment by evancz** [comment]
Seems like a job for a weird special case `if`.

**Comment by vilterp** [comment]
Yup!

**Comment by 0xR** [comment]
I'm trying out elm for the first time and I'm also running into this issue. Less than ideal developer experience. +1 to fix this

**Comment by spinningarrow** [comment]
Having the same issue. Am I doing something wrong?

**Comment by b2whats** [comment]
also get this error, how to fix it ?

**Comment by tamlyn** [comment]
This makes me sad 😕

**Comment by ccorcos** [comment]
+1

**Comment by stil4m** [comment]
+1

**Comment by sectra-masve** [comment]
Tried elm for the first time today, using the Hello World examples project. The first thing I see are errors like this.

**Comment by lovasoa** [comment]
+1
