### ISSUE TITLE
NPM Installation, No _reactor/debug.js

### ISSUE THREAD

**Issue by semperos** [elm-lang/elm-reactor#125]
I see this problem has been discussed quite a bit in the mailing list and other Github issues. I believe this is a unique manifestation of the problem.

Setup:

 * Ubuntu 15.04
 * Node versions tried: v0.10.40, v0.12.7, Io.js v2.3.4
 * Elm Reactor 0.3.2 (Elm Platform 0.15.1)
 * Elm installed via `npm install -g elm`

New project, single `Main.elm` file with content:

```elm
import Text exposing (..)
import Color exposing (..)
import Graphics.Element exposing (..)
import Graphics.Collage exposing (..)

diamond color size =
  square size |> filled color |> rotate (degrees 45)

main = collage 200 200 [ diamond blue 100, diamond red 75 ]
```

Fresh `elm-make Main.elm --output index.html` seems to work as expected. Running `elm-reactor` boots up the server, `Main.elm` and `index.html` appear as expected. But trying to use the debug version, the `/_reactor/debug.js` file cannot be found.

I see that this file exists in all three versions of Node.js/Io.js I tried this with:

```
./.nvm/versions/io.js/v2.3.4/lib/node_modules/elm/share/reactor/_reactor/debug.js
./.nvm/versions/node/v0.12.7/lib/node_modules/elm/share/reactor/_reactor/debug.js
./.nvm/v0.10.40/lib/node_modules/elm/share/reactor/_reactor/debug.js
```

It just appears that I'm either missing a step, or `elm-reactor` is not pulling these files into place as intended. I also set `ELM_HOME` to the correct value under each version of Node that I tried when running `elm-make` and `elm-reactor`, not knowing if that would make a difference.

Any help would be greatly appreciated.

**Comment by semperos** [comment]
Simply doing a `cp -R <location of _reactor> .` in my project appears to pull in all that is required, I can see hot swapping working. I can certainly add that `cp` to a build step, but the documentation seems to suggest this shouldn't be necessary.

**Comment by jvoigtlaender** [comment]
The [README of the npm installer](https://github.com/kevva/elm-bin), also [here on the official npm site](https://www.npmjs.com/package/elm), says:

"Also, set the `ELM_HOME` environment variable to `/usr/local/lib/node_modules/elm/share` or the corresponding directory created on your machine."

This is what you have to do.

Of course, it would be nice if instead the npm installer would set the path itself. There's an [issue for that](https://github.com/kevva/elm-bin/issues/22). If you know how to do that on the npm installer's side, maybe propose a solution there?

**Comment by semperos** [comment]
@jvoigtlaender Thank you. I was setting `ELM_HOME`, per my original post, but I misread the instructions and was setting it to `../node_modules/elm` instead of all the way to `../node_modules/elm/share`.

Thanks. I'll mark this as closed for elm-reactor. I really appreciate the quick and friendly response.
