### ISSUE TITLE
Event counter alternates after swap if it has timers

### ISSUE THREAD

**Issue by vilterp** [elm-lang/elm-reactor#126]
To reproduce:

1. Open clock example (below)
2. wait for it to tick a while (to step `x`)
3. edit, causing swap. module has paused, but event count keeps going up (?)
4. press pause & play to restart it (see other bug TODO).

The clock hand starts ticking again, but the event count on the scrub slider is *alternating* between lower and higher values (both ticking up)

This alternation doesn't happen if you repeat the same process on a module without timers (e.g. stamps or keyboard examples).

```elm
import Color exposing (..)
import Graphics.Collage exposing (..)
import Graphics.Element exposing (..)
import Time exposing (..)


main =
  Signal.map clock (every second)


clock t =
  collage 400 400
    [ filled lightGrey (ngon 12 110)
    , outlined (solid grey) (ngon 12 110)
    , hand red 100 t
    , hand charcoal 100 (t/60)
    , hand charcoal 60 (t/720)
    ]


hand clr len time =
  let
    angle = degrees (90 - 6 * inSeconds time)
  in
    segment (0,0) (fromPolar (len,angle))
      |> traced (solid clr)
```

**Comment by evancz** [comment]
I would guess that this is related to the `asyncCallbacks` array. It was never clear to me if that should be all the async callbacks ever, or just the currently pending ones. Point is, I bet there is a problem there and it *could* explain this.
