### ISSUE TITLE
Editor window for code (enhancement)

### ISSUE THREAD

**Issue by JustusAdam** [elm-lang/elm-reactor#132]
How about adding the option for a (javascript) editor for code files. 

There's an elm code editor out there already (the try elm page) why not integrate that editor into the reactor? We already have it running as a server, why not enable it to be sort of a web-based elm IDE?

**Comment by evancz** [comment]
The goal here is not to make an IDE, it is to make a development helper that pairs with whatever your favorite editor is. No matter how well we do, it will still be emacs vs vim or sublime vs atom or whatever. I don't want to get core tools into that fight.
