### ISSUE TITLE
Debugger crashes when code uses Time.delay

### ISSUE THREAD

**Issue by wetmore** [elm-lang/elm-reactor#136]
The `Time.delay` function creates a node in the signal graph with no kids. This means any module using delay cannot be opened in the reactor debugger, because the following code in `debug.js` will throw an error:

```javascript
function addAllToDict(node)
	{
		nodesById[node.id] = node;
		node.kids.forEach(addAllToDict);
	}
	nodes.forEach(addAllToDict);
```

`node.kids` is undefined for an output-delay-output-n node (where n is the delay in millis).

I don't know much about the signal implementation so I don't know if the lack of kids is intentional, but if it is the debugger code should account for this. Otherwise it's impossible to use the debugger on code with `delay` which is a bummer.

**Comment by vilterp** [comment]
Looks like I accounted for this case in my ongoing reactor work (^ in the PR above). Was unable to reproduce this bug with the following code:

```elm
module Delay where

import Mouse
import Time
import Html exposing (..)
import Signal

main =
  Signal.map (\n -> text (toString n)) state

state =
  Signal.foldp (\_ n -> n + 1) 0 (Time.delay 500 Mouse.clicks)
```

**Comment by evancz** [comment]
Cool, thanks for migrating the issue @wetmore, and glad it is getting sorted out in the next release!
