### ISSUE TITLE
Pure elm Task and Port runtime error.

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-reactor#137]
Ok, this reproduces easily:

```elm
module Main where

import Graphics.Element exposing (..)
import Signal exposing (..)
import Task exposing (..)
import Keyboard

type Input = Input

input : Mailbox Input
input =
  mailbox Input

createKey : Signal (Task x ())
createKey = let
  create : Task x ()
  create = Signal.send (.address input) Input
  in Signal.filterMap
    (\b -> if b then Just create else Nothing)
    create
    Keyboard.enter

port run : Signal (Task x ())
port run = createKey

main : Signal Element
main = show <~ input.signal
```

**Comment by vilterp** [comment]
Can you add the runtime error to the issue description? Currently hard to tell what this issue is about.

**Comment by Fresheyeball** [comment]
![screen shot 2015-08-07 at 6 00 45 pm](https://cloud.githubusercontent.com/assets/609279/9148039/4552026e-3d2e-11e5-85e8-9d1f594eb590.png)

**Comment by vilterp** [comment]
Great, thanks. Will take a look at this.

**Comment by aymanosman** [comment]
I have also had this issue. And a couple of others with the time travelling debugger.

![elm-bork](https://cloud.githubusercontent.com/assets/3605049/9274969/e7ccf54a-4291-11e5-833f-e03a457da344.png)
