### ISSUE TITLE
fail gracefully when there is no exact-dependencies.json

### ISSUE THREAD

**Issue by vilterp** [elm-lang/elm-reactor#144]
Instead of showing this:

```
A web handler threw an exception. Details:
elm-stuff/exact-dependencies.json: openBinaryFile: does not exist (No such file or directory)
```

Also, this is more work, but it would be nice to offer a button triggering `elm-package install` if there's an elm-package.json but not an exact-dependencies.json.

**Comment by evancz** [comment]
I fixed this
