### ISSUE TITLE
"Uncaught TypeError" when running elm-architecture-tutorial example 5 in debug mode

### ISSUE THREAD

**Issue by sykesd** [elm-lang/elm-reactor#145]
I am just trying to learn Elm and have been working my way through the elm-architecture-tutorial. When I tried to run example 5 in debug mode I received the runtime exception mentioned in the subject.

More details below. I was testing in Chrome, but the same (or very similar) error occurs in Firefox and IE.

# Environment
Windows 7 64-bit
Elm Platform 0.15.1
Elm Reactor 0.3.2
Chrome 44.0.2403.155 m

# Output
    Cannot read property 'forEach' of undefined
    
    
    Open the developer console for more details.

# Javascript stack trace
    Uncaught TypeError: Cannot read property 'forEach' of undefined
        addAllToDict @ debug.js:15449
        addAllToDict @ debug.js:15449
        addAllToDict @ debug.js:15449
        addAllToDict @ debug.js:15449
        flattenSignalGraph @ debug.js:15451
        initAndWrap @ debug.js:15504
        make @ debug.js:14979
        init @ Main.elm?debug:8510
        Elm.fullscreen @ Main.elm?debug:8393
        initModuleWithDebugState @ debug.js:14985
        Elm.fullscreenDebug @ debug.js:14909
        (anonymous function) @ Main.elm?debug:13883

**Comment by evancz** [comment]
I believe this is fixed in the development version of `core`. I think @vilterp or @jvoigtlaender might be able to confirm. I certainly remember accepting a pull request for this issue, but I forget if it was for core or elm-reactor.

**Comment by amitaibu** [comment]
> I believe this is fixed in the development version of core

What's the proper way of testing the dev version - Is it [this](https://github.com/elm-lang/elm-platform#build-from-source)?

**Comment by jvoigtlaender** [comment]
@amitaibu, that's how `elm-compiler`, `elm-reactor` etc. are built. To "just" test the current version of `core`, you check out the master branch of https://github.com/elm-lang/core and run your tests in that directory. However, to test interaction of `core` and debug mode, things are more complicated. The thing is that when running code in `elm-reactor`, a different version of `core` may be used then the one you downloaded by hand (namely, the one that was used when compiling the `elm-reactor` exectuable). So you would indeed have to use the `BuildFromSource.hs` approach to compile your own version of `elm-reactor`, but *also* make sure that that build does not pull in version `2.1.0` of `core`, but instead the `master` branch of https://github.com/elm-lang/core.

**Comment by rtorr** [comment]
@jvoigtlaender @amitaibu

Relevant information on that process:
https://github.com/elm-lang/elm-lang.org/pull/366/files

**Comment by flip111** [comment]
I also have this issue, if someone can tell me where the PR is i can hotpatch this code until the next official release is available.

**Comment by permelin** [comment]
I confess that I haven't tried to combine reactor with the latest development core, but I have doubts that it fixes the problem.

Signal.js adds a `kids` attribute to all nodes **except** output nodes:
https://github.com/elm-lang/core/blob/master/src/Native/Signal.js#L94-L98

The reactor debugger expects *all* nodes to have `kids`:
https://github.com/elm-lang/elm-reactor/blob/master/frontend/debugger-implementation.js#L724

So anytime your program has a port you get a runtime error in debug mode.

I'm not familiar enough with the code to say whether Signal.js should add `kids` to output nodes, or the debugger should check for `node.isOutput` as Runtime.js does.

**Comment by permelin** [comment]
I was stumped as to why only ports were a problem and not the main output signal, but after further reading of the code I can see that the main output is only wired into the signal graph after the problematic function in the debugger is triggered.

It now seems clear to me that the right thing to do is to add a check for node.isOutput when traversing in the debugger.

**Comment by download13** [comment]
Is this fix going to be released soon?

**Comment by frontsideair** [comment]
I experienced this problem as well just now. Elm Reactor version: 0.16.0

**Comment by evancz** [comment]
Gone for now, can open a new issue if it resurfaces in future releases.
