### ISSUE TITLE
Hotswap CSS ?

### ISSUE THREAD

**Issue by rundis** [elm-lang/elm-reactor#152]
I'm coming from a Clojure/ClojureScript background using a tool called [figwheel](https://github.com/bhauman/lein-figwheel). elm-reactor has quite a few overlapping features, especially when hot-swap is working that is ! 

What would be really cool would be the ability to hot-swap css as well. 
Say you have an external html file which embeds elm (Elm.fullscreenDebug...) referring to one or more css files. When I change one of the referred css files, it would be nice if reactor picked up this fact and sent the updated css to the browser. It would make the web-app development experience even nicer.

It's not that doing a manual page reload is that hard, but in a single page app having to repeadedly click through your app to get to the state you wish to test in, is where productivity goes downhill :)

**Comment by joshmh** [comment]
See also #138

**Comment by evancz** [comment]
Tracking in #193, follow along there!
