### ISSUE TITLE
hot-swapping loosing signals

### ISSUE THREAD

**Issue by zilvinasu** [elm-lang/elm-reactor#153]
Hey,

I tried to use this example https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/1/Counter.elm running `elm-reactor`  then editing some action like Increment or Decrement, code changes seem to be swapped but application itself seems to loose ability to receive any signals and looses onClick events.

**Comment by jvoigtlaender** [comment]
This is a known issue already reported.

**Comment by zilvinasu** [comment]
Seems to be a duplicate of #127
