### ISSUE TITLE
"permission denied" when the file to load (and its dependencies) causes a syntax error on Windows

### ISSUE THREAD

**Issue by igrep** [elm-lang/elm-reactor#155]
# Problem

When opening a file which causes a syntax error on elm-reactor, I always got such an error message:

```
A web handler threw an exception. Details:
terminateProcess: permission denied (Permission denied)
```

And this happens when any dependencies of the file to open cause syntax error.

# About my env

- OS: Windows 10
- elm reactor: 0.16.0 (installed from the [Elm 0.16 - pre-release thread](https://groups.google.com/forum/#!topic/elm-dev/7daC5GV_wao))

**Comment by jvoigtlaender** [comment]
@evancz, this appears to be the same error I reported on the dev list. It means that anybody having this issue will be essentially banned from using `elm-reactor`. Do you really want to release `0.16` with this in?

**Comment by jvoigtlaender** [comment]
Let my also repeat my suspicion: This is caused by the `================= ERRORS ==============` line that you add now (sometimes) to the output. Do you somehow add it in a way that is different from "normal" output?

**Comment by evancz** [comment]
I'll have a new installer with a probable fix out in a bit. I cc'd @jvoigtlaender on the change if you want to link it here.

**Comment by jvoigtlaender** [comment]
So, for the record, the fix was https://github.com/elm-lang/elm-make/commit/931385e2eddfd31c6b0f329bdf4e692cb29d6d89.

**Comment by evancz** [comment]
Okay, when you download the installer now, it should point to the fixed version.

@jvoigtlaender or @igrep, can you download the new one and try it out? Let me know what happen!

**Comment by igrep** [comment]
From the same link on [Elm 0.16 - pre-release thread](https://groups.google.com/forum/#!topic/elm-dev/7daC5GV_wao) right? Wait a minute.

**Comment by evancz** [comment]
Yep, that's the one: http://install.elm-lang.org/Elm-Platform-0.16.exe

I did a refresh of the CDN that serves it so it should be the new one.

**Comment by igrep** [comment]
It worked! :smile: Thanks!

```
Detected errors in 1 module.
-- SYNTAX PROBLEM ------------------------------------ src/IgrepCashbook/App.elm

I ran into something unexpected when parsing your code!

47│           , summary <- Summary.calculate <| FileList.collectCalculatedFiles m.fileList
                        ^
I am looking for one of the following things:

    an equals sign '='
    whitespace
```

**Comment by evancz** [comment]
Hell yes! :D Thanks for the report and trying it out so quick!

**Comment by evancz** [comment]
@jvoigtlaender, how about your thing?

**Comment by jvoigtlaender** [comment]
Same here. Works now, I see the error message in the browser.

**Comment by evancz** [comment]
Great, thanks for reporting and working through this with me!
