### ISSUE TITLE
"_U.list is not a function" When debugging with elm 0.16

### ISSUE THREAD

**Issue by burabure** [elm-lang/elm-reactor#156]
Updated to 0.16 and now I'm getting this error when debugging, I think it's a runtime error and not a compile time one. Non debugging compiles and runs fine.

**Comment by jvoigtlaender** [comment]
Are you sure that in addition to updating to 0.16 your `ELM_HOME` environment variable is also now pointing to 0.16's `share` directory, instead of still to 0.15's or 0.15.1's?

**Comment by burabure** [comment]
I thought that ELM_HOME wasn't needed for 0.16 (or at least that was the idea). having to check and set it every time is a downer =(

Anyways changed it to ``` ~/.nvm/versions/node/v4.2.1/lib/node_modules/elm/Elm-Platform/0.16.0/share ``` and it's still giving me the same error

**Comment by fredcy** [comment]
I'm also seeing a fatal "not a function" error in javascript console when using the 0.16 elm reactor in debug mode. I don't have ELM_HOME set. Running in Mac OS X with 0.16 installed from package.

**Comment by fredcy** [comment]
Seems to be happening at debug.js:9560:26.

```javascript
Elm.Native.Slider.make = function(localRuntime) {
```

**Comment by burabure** [comment]
@fredcy I think you should try setting it. take a look at https://github.com/elm-lang/elm-reactor/issues/131#issuecomment-123402958

**Comment by fredcy** [comment]
I tried with ELM_HOME set (to /usr/local/share/elm) and I get the same error as before.

**Comment by jvoigtlaender** [comment]
@burabure, I also thought that 0.16 would obviate `ELM_HOME`. But this morning I [learned](https://github.com/elm-lang/elm-platform/pull/110#issuecomment-157969775) that this will only happen with the next release of `elm-reactor`, probably in 0.16.1.

@fredcy, what are the contents of your `/usr/local/share/elm`? Is there a file `/usr/local/share/elmreactor/_reactor/debug.js`?

**Comment by burabure** [comment]
@jvoigtlaender bummer =( Would uploading my code to a repo help you help me solving this error?

**Comment by jvoigtlaender** [comment]
I'm not really an expert in `elm-reactor` things (apart from managing its build plan etc. in https://github.com/elm-lang/elm-platform). Maybe @vilterp knows what happened to `_U`, specifically.

**Comment by fredcy** [comment]
Looks like a semi-colon is missing at debug.js:9637, the end of the Elm.Native.Slider.make function.

**Comment by burabure** [comment]
@fredcy looks fine to me 
```
return localRuntime.Native.Slider.values = {
        slider: F2(slider)
    };
```

**Comment by fredcy** [comment]
https://github.com/elm-lang/elm-reactor/blob/0.16/frontend/Native/Slider.js

**Comment by fredcy** [comment]
If I patch debug.js to add that semicolon I get past the fatal "not a function" error.

But then I get an error about "up.props is undefined" appearing in the right pane of the reactor window.  That's happening in the customButton() function.

**Comment by jvoigtlaender** [comment]
@evancz, it seems `elm-reactor` as shipped with 0.16 is broken in debug mode.

**Comment by tcoopman** [comment]
I have the same error, installed 0.16 from npm on linux

**Comment by zilvinasu** [comment]
Same problem with 0.16 on Mac OS X

**Comment by tcoopman** [comment]
It looks like someone also has the problem with http://elm-lang.org/try: https://www.reddit.com/r/elm/comments/3tg8es/016_compiler_problem/

**Comment by evancz** [comment]
There is a new version of elm-reactor that is a ton better, so I am just going to focus on getting that ready real quick. There may be a week or two in the meantime, but if you are able to start tracking down the root issues here please do a PR and @ mention me.

**Comment by flip111** [comment]
@evancz what are the new features and/or improvements in the new version of the elm-reactor?

**Comment by jvoigtlaender** [comment]
@flip111, why is that relevant at this point? Isn't it more useful to get it fixed and released as soon as possible (then with a blog post advertising the improvements) than taking time now to detail the improvements here and now, for a limited audience?

**Comment by flip111** [comment]
it's not relevant, i was just curious ... perhaps there is a list somewhere already

**Comment by jvoigtlaender** [comment]
There are for sure discussions (and, if I remember correctly, mock ups of the UI) on one of the mailing lists.

**Comment by evancz** [comment]
So the root here was that ELM_HOME is still needed? If so, let's close it. This is going to be fixed in the next release of the platform, it cannot be done as a patch.

**Comment by burabure** [comment]
it was the missing semicolon that 6db89d08e83d5a50fef26c28610646679c23bce1 solved, so we can close this =)

**Comment by evancz** [comment]
Cool, thanks for the report and for letting us know what happened in the end!

**Comment by Milanvdm** [comment]
I still have this problem.

**Comment by jvoigtlaender** [comment]
@Milanvdm, still? Have you re-installed 0.16 and the `core` package after Evan's fix?
