### ISSUE TITLE
elm-reactor: pressing restart throws error

### ISSUE THREAD

**Issue by hkrish** [elm-lang/elm-reactor#167]
I have built elm-platform from the master as of today. If I load one of the examples, interact with it a bit, and press the reload button, I get this error *in firefox*.

    TypeError: event is undefined
        initAndWrap/runtime.timer.now()           debug.js:12209
        initAndWrap/debugState.refreshScreen()    debug.js:12180
        restart()                                 debug.js:11749
        Elm.fullscreenDebug/<()                   debug.js:11629
        notify()                                  debug.js:1225
        output/node.notify()                      debug.js:3377
        broadcastToKids()                         debug.js:3294
        mapMany/node.notify()                     debug.js:3415
        broadcastToKids()                         debug.js:3294
        input/node.notify()                       debug.js:3317
        notify()                                  Main.elm:1324
        send/</<()                                debug.js:3341

*In chrome*:

    Uncaught TypeError: Cannot read property 'time' of undefined                      debug.js:12209

Seems like it is the same issue as #122

**Comment by kaikuchn** [comment]
It is the same error as in #122 and #168, so I guess you can close this one @hkrish

**Comment by hkrish** [comment]
Yup they seems to be the same.
