### ISSUE TITLE
No hot swapping occurs on OS X, Linux; TypeError: undefined is not an object (evaluating 'event.time')

### ISSUE THREAD

**Issue by tel** [elm-lang/elm-reactor#168]
When running elm-reactor on a fresh Elm Platform install on OS X hot swapping does not occur (tested Chrome and Safari). Furthermore, when clicking the "refresh" icon I see errors like

```
Uncaught TypeError: Cannot read property 'time' of undefined
runtime.timer.now @ debug.js:12209
debugState.refreshScreen @ debug.js:12180
restart @ debug.js:11749
(anonymous function) @ debug.js:11629
notify @ debug.js:1225
node.notify @ debug.js:3377
broadcastToKids @ debug.js:3294
node.notify @ debug.js:3415
broadcastToKids @ debug.js:3294
node.notify @ debug.js:3317
notify @ Tut.elm?debug:1324
(anonymous function) @ debug.js:3341
```

The relevant line in `debug.js` looks like

``` javascript
	runtime.timer.now = function() {
		if (debugState.paused || debugState.swapInProgress)
		{
			var event = debugState.events[debugState.index];
			return event.time;
		}
		return Date.now() - debugState.totalTimeLost;
	};
```

**Comment by ccorcos** [comment]
+1

**Comment by ronnross** [comment]
hot swapping doesn't work on windows as well. I'm running elm 0.16.

**Comment by thisredone** [comment]
Doesn't seem to work on linux also
tested on Ubuntu 15.10 (and Windows 8.1)

**Comment by maxgurewitz** [comment]
+1

**Comment by fourcube** [comment]
I've investigated a little and found the following:

1. A file system monitor is registered that watches for changes to files with a suffix of `elm`. It looks like the suffix has to actually contain the dot (`.`) so the monitoring works. This is fixed in #170 and should resolve the problem for linux users.

2. Under OSX (10.11, ghc 7.10.2) there seems to be another problem. Data is **only partially** written to the client websocket connection. 

When I send dummy data over the websocket in the `sendHotSwap`function 

```haskell
--- ... e.g.
sendHotSwap :: FilePath -> WS.Connection -> FilePath -> IO ()
sendHotSwap watchedFile connection _ =
  do  result <- liftIO (Compile.toJson watchedFile)
      _ <- WS.sendTextData connection (BSC.pack $ concat $ replicate 0xFFFF "foo")
      WS.sendTextData connection (BSC.pack result)

--- ...
```

, before sending the actual compiled code, everything goes through just fine. This is obviously no proper solution to the problem. I was suspecting TCP_NODELAY on this one, but it should be disabled in Snap and https://github.com/jaspervdj/websockets by default.

**Comment by swirlycheetah** [comment]
Is there any update on this? I really want to show off some of the developer experience features Elm offers to some colleagues but currently can't.

**Comment by zhulongzheng** [comment]
+1

**Comment by jonathanp** [comment]
I just ran into this bug as well.

**Comment by rapind** [comment]
This is such a huge and cool feature. Can't wait to get it back! :+1:

**Comment by ronnross** [comment]
Alright I put a call out on Elm discuss to pair with someone to fix this issue. I will definitely need some help with the Haskell part. Wish me luck in getting this working again fast.

**Comment by jvoigtlaender** [comment]
Note, though, that there are several branches in this repository that are upwards of 100 commits ahead of the `master` branch.

**Comment by huiwang** [comment]
please fix it. it's so wanted.

**Comment by pukkamustard** [comment]
Having the same problem on OS X.

**Comment by EddyLane** [comment]
+1 on OSX, would love to help but I don't think I have the chops yet, elm is on like every other podcast at the moment so it'd be great to get this working again as I think its one of the major selling points bringing new people to the language

**Comment by seanhess** [comment]
Sad. I'm set to present this morning on Elm. Thank you for working on the fix! @ronnross did you get the pairing help you need? If not I'd be glad to volunteer.

**Comment by ronnross** [comment]
@seanhess no one really volunteered to pair, but it looks like others have started working on a node port. I'm not 100% sure of the state. It lives here https://github.com/eeue56/elm-reactor/tree/node-rewrite. If you are interested in pairing up message me at [http://elmlang.herokuapp.com/](http://elmlang.herokuapp.com/)

**Comment by seanhess** [comment]
Ok, I signed up and messaged you on slack. LMK if this is worth doing. I
have next week off so I'll have plenty of time.

**Comment by dusky3** [comment]
Just to let you know that hot swapping doesn't work on 64bit Void linux with Firefox as well.

**Comment by d4rkr00t** [comment]
Hi it happens on OSX 10.11 and 10.10 with elm and elm reactor 0.16.0.

**Comment by despairblue** [comment]
@tel hey, could you rename the issue to make it clear that all platforms are affected? ty :bow:

**Comment by tel** [comment]
Good idea!

**Comment by qisaw** [comment]
This doesn't seem to work on Windows 10 either. Any update on when this will be fixed?

**Comment by bassmake** [comment]
+1

**Comment by fourcube** [comment]
For anyone who has this problem under linux, @pgaertig posted a possible solution here:

 https://github.com/elm-lang/elm-reactor/pull/170#issuecomment-210919790

**Comment by chroth7** [comment]
Sorry to bring that up again - but in my case (using 0.17 on OSX), I still do not see any hot-swapping happening. I did read here https://groups.google.com/forum/#!topic/elm-discuss/2GzFng0utro that the time-travelling debugging is currently not possible (0.17), is that something similar here?

Thanks for a clarification (if I misunderstand, I am happy to look at my config again.

**Comment by evancz** [comment]
It's all coming back.
