### ISSUE TITLE
elm-reactor VS elm reactor

### ISSUE THREAD

**Issue by aestheticsdata** [elm-lang/elm-reactor#169]
Should I use : 
```
elm-reactor
````
or : 
```
elm reactor
```
Thanx.

**Comment by jvoigtlaender** [comment]
The two should be equivalent, but might not, if your install is borked.

**Comment by ronnross** [comment]
I'm not sure with the release you download from the website, but if you install [elm from npm](https://www.npmjs.com/package/elm). You only have the option of elm-*. I don't know if this helps, but I would probably just use elm-*.

**Comment by igrep** [comment]
@ronnross Unfortunately, yours also doesn't seem to be installed properly.
Both of them work on my Arch Linux's install.
What's printed by `elm reactor --version` and `elm-reactor --version` on your machine?

**Comment by ronnross** [comment]
@igrep I totally made a mistake both `elm reactor --version` and `elm-reactor --version` works with the version installed from npm. My mistake.

**Comment by AppSynergy** [comment]
Aside:  I always go for `elm-rea<tab>` for auto-complete goodness.

**Comment by jvoigtlaender** [comment]
@aestheticsdata, can you please close this issue? It seems your question was answered. If not, what additional information do you need?

**Comment by turboMaCk** [comment]
I think this can be closed.
