### ISSUE TITLE
Uncaught Error: The notify function has been called synchronously! This can lead to frames being dropped. 

### ISSUE THREAD

**Issue by despairblue** [elm-lang/elm-reactor#171]
See https://github.com/elm-lang/elm-compiler/issues/1122

from my chrome console:
```
Uncaught TypeError: Cannot read property 'time' of undefined

Uncaught Error: The notify function has been called synchronously!
This can lead to frames being dropped.
Definitely report this to <https://github.com/elm-lang/Elm/issues>
```

elm@0.16.0

**Comment by despairblue** [comment]
Happens when running the input example (I can't link to it right now, since elm-lang.org is down) and pressing this button in the debugger:

![screen shot 2015-12-13 at 19 33 23](https://cloud.githubusercontent.com/assets/927609/11768531/85fbb740-a1d0-11e5-8223-2e8df045e22b.png)

**Comment by ravicious** [comment]
Looks like a duplicate of #122 and #168. :grin:

**Comment by jvoigtlaender** [comment]
@despairblue, is it a duplicate of those issues mentioned above? If so, please close here.

**Comment by despairblue** [comment]
@jvoigtlaender right, could be that this error is the consequence of #122.

I'll close it and investigate a bit.
