### ISSUE TITLE
Cannot read property 'forEach' of undefined in debugger

### ISSUE THREAD

**Issue by marcosh** [elm-lang/elm-reactor#175]
I have a working application in Elm. When I try to open the debugger, it crashes with the error reported in the title of the issue.

The problem happens at line 12136 of the file `debug.js`, that is

    node.kids.forEach(addAllToDict);

The error happens because the `kids` property of the `node` object is undefined.

For debugging purposes, when the function `addAllToDict` is called, this is the structure of the `node` object:

    Object {
        id: 1
        kids: Array[1]
            0: Object
                id: 2
                kids: Array[2]
                    0: Object
                    1: Object
                        id: 5
                        kids: Array[1]
                            0: Object
                                id: 6
                                isOutput: true
                                name: "output-perform-tasks-tasks"
                                notify: (timestamp, parentUpdate, parentID)
                                parents: Array[1]
                                __proto__: Object
                            length: 1
                            __proto__: Array[0]
                        name: "map1"
                        notify: (timestamp, parentUpdate, parentID)
                        parents: Array[1]
                        value: Object
                        __proto__: Object
                    length: 2
                    __proto__: Array[0]
                name: "foldp"
                notify: (timestamp, parentUpdate, parentID)
                parents: Array[1]
                value: Object
                __proto__: Object
            length: 1
            __proto__: Array[0]
        name: "input-mailbox"
        notify: (timestamp, targetId, value)
        parents: Array[0]
        value: Object
        __proto__: Object

You can notice that the "output-perform-task-task" node does not have a `kids` property

**Comment by jvoigtlaender** [comment]
This is a duplicate. Please check other issues and close this one.
