### ISSUE TITLE
TypeError: node.kids is undefined

### ISSUE THREAD

**Issue by ogzogz23** [elm-lang/elm-reactor#176]
I ran into this error when I tried to use the Time Traveling Debugger (clicking on the wrench)

Running without the Time Traveling Debugger is fine.

The code I was running was from elm-architecture-tutorial
(example 5)

Stack Trace:

addAllToDict() debug.js:12136
forEach() self-hosted:211
addAllToDict() debug.js:12136
forEach() self-hosted:211
addAllToDict() debug.js:12136
forEach() self-hosted:211
addAllToDict() debug.js:12136
forEach() self-hosted:211
flattenSignalGraph() debug.js:12138
initAndWrap() debug.js:12191
make() debug.js:11666
init() mainEffects.elm:1391
Elm.fullscreen() mainEffects.elm:1274
initModuleWithDebugState() debug.js:11672
Elm.fullscreenDebug() debug.js:11596
<anonymous> mainEffects.elm:12324

**Comment by jvoigtlaender** [comment]
This has been reported many times. No new ticket is required, so please close it as a duplicate.

Some existing open tickets about this are https://github.com/elm-lang/elm-reactor/issues/145 and https://github.com/elm-lang/elm-reactor/pull/149 (and there are various closed duplicates as well).

**Comment by ogzogz23** [comment]
oops sorry
