### ISSUE TITLE
Feature Request: Integrate docs preview

### ISSUE THREAD

**Issue by creationix** [elm-lang/elm-reactor#177]
I've been so spoiled by using elm-reactor for development that it seems almost painful to have to run `elm --make=documentation.json` in a terminal window, and then go to a browser window at http://package.elm-lang.org/help/docs-preview and click on upload and find the file and click ok.

Instead I'd like to just have a tab open with reactor pointing to my file with `?docs-preview` or something appended.  Then I could just save in editor, and refresh browser.

**Comment by thefakezymurg** [comment]
There definitely needs to be something like this. I've been coding on a Chromebook, so there are even more annoying steps involved in previewing docs.

**Comment by evancz** [comment]
Makes sense to me! Adding to #193 so all these ideas show up in one place. This'll make it easier to make it all happen in a coherent way.
