### ISSUE TITLE
Debugger is frozen in 0.16

### ISSUE THREAD

**Issue by tomekwi** [elm-lang/elm-reactor#178]
Hello, I installed *elm reactor* via the *npm* installer on a Fedora machine. Though [`Mario.elm`](https://github.com/evancz/elm-examples/blob/2185a6e680e350967fb58999faabb5bf13c9b16a/Mario.elm) from *elm-examples* directly works OK when started directly, it’s completely frozen in debug mode. Hitting arrow keys has no effect. Resizing the window doesn’t trigger a redraw:

![selection_003](https://cloud.githubusercontent.com/assets/4624660/12797388/02f090d8-cac4-11e5-87ea-22342a64f478.png)

![selection_005](https://cloud.githubusercontent.com/assets/4624660/12797423/28f1ece6-cac4-11e5-88b4-8374cacf6efe.png)

Other examples do work, but hot reloading doesn’t – as @janraasch described in https://github.com/elm-lang/elm-reactor/issues/157#issuecomment-158879715.

**Comment by janraasch** [comment]
I would love to see this getting fixed. Let me know, if you need more details.

**Comment by tomekwi** [comment]
@evancz @rtfeldman perhaps [elm-lang/elm-platform](https://github.com/elm-lang/elm-platform) is a better place to report this?

**Comment by rtfeldman** [comment]
Doubt it's npm related. reactor is pretty broken in 0.16 unfortunately :x

**Comment by tomekwi** [comment]
I’ve tried installing *elm-platform* from source – but it still doesn’t work. Same symptoms. :disappointed:

@rtfeldman, would you share an insight into your workflow then? http://git.io/elm-live is a pain in serious apps because it loses state across reloads. Watches also seem to be extremely useful. Do you recommend staying with *0.15.1*?

**Comment by rtfeldman** [comment]
@tomekwi We have a non-SPA with Rails 3 on the backend, so basically everything is recompiled on page load. It's more accurate to say "we're working on it" than that "we're happy with it." :smile: We're in the process of migrating to webpack, and will definitely post something if we get that resolved!

**Comment by tomekwi** [comment]
Haha, I know this feeling! Good luck then! I can’t wait!

**Comment by tomekwi** [comment]
@janraasch @rtfeldman @evancz

I went ahead and updated [git.io/elm-live](https://git.io/elm-live) to be independent of *elm-reactor*.

It isn’t as fancy as *elm-reactor* (no hot reloading, no time-travel debugger). But it’s supposed to be more flexible. It’s dead easy to do fancy stuff like custom HTML and CSS.

I don’t know about dynamic backends like Rails. Maybe it could connect with those as well – it probably depends on how the frontend and backend are connected.

**Comment by evancz** [comment]
Will be done a different way in a future release.
