### ISSUE TITLE
Feature request: change base url

### ISSUE THREAD

**Issue by Zimmi48** [elm-lang/elm-reactor#180]
Hello,

I'm trying to debug Elm in the cloud using SageMathCloud (cloud.sagemath.com) and elm-reactor.
From this plateform, you can run a server and access it in the browser but not at a simple URL such as http://0.0.0.0:8000/ but rather at https://cloud.sagemath.com/my-project-id/port/my-port/.
When doing so, I currently bump into a blank page. Is there any way to specify to elm-reactor to ignore the base URL my-project-id/port/my-port/ or would adding this option to elm-reactor be somehow easy to do?

Thanks,
Théo

PS: my current work around is to create a symlink from my-project-id/port/my-port/ to my base directory.

**Comment by Zimmi48** [comment]
For info, since 0.17, the workaround I had found does not work any longer.
The generated HTML tries to load a script at https://cloud.sagemath.com/_compile/my-project-id/port/8000/Main.elm and this obviously is not going to work (it should rather be https://cloud.sagemath.com/my-project-id/port/8000/_compile/Main.elm).

PS: Feel free to close the issue if that's not something you want to solve.

**Comment by evancz** [comment]
I do not see a clear route to resolving this, so I guess it makes sense to close. Perhaps there is some way, but it makes sense to open that as a separate issue when someone thinks of it.
