### ISSUE TITLE
No wrench

### ISSUE THREAD

**Issue by ccorcos** [elm-lang/elm-reactor#182]
![image](https://cloud.githubusercontent.com/assets/1794527/15166814/63680a9a-16d7-11e6-92aa-3a209852e36e.png)

**Comment by evancz** [comment]
Yes, in the interest of releasing 0.17 I had to cut this feature. The runtime system changed dramatically, so it was not a simple thing to just fix. This stuff will be coming back with a stronger focus on "what people actually need for development" so hold on to your horses.

**Comment by adicirstei** [comment]
So, as for now, `elm-reactor` is just a web server?

**Comment by evancz** [comment]
Yeah, it just is meant to help beginners begin. That's really been the top practical strength for quite some time.

**Comment by MichaelRFairhurst** [comment]
Are there any tickets or anything on the steps to fix this? I'd be interested in helping get it working again
