### ISSUE TITLE
HTML files no longer being served in 0.17

### ISSUE THREAD

**Issue by deepilla** [elm-lang/elm-reactor#184]
As discussed [here](https://groups.google.com/forum/#!topic/elm-discuss/obnoFEWiIlE "Elm Discuss: Has elm reactor 0.17 dropped support for HTML files?"), elm-reactor 0.17 displays HTML files as plain text instead of serving them as HTML (as it used to in 0.16). So if you embed Elm into a custom HTML file it is no longer possible to run your app from http://localhost:8000/custom.html. All you get is the source code.

Is support for HTML files coming back? Embedding Elm in HTML must be common practice. Losing access to the main dev/debug environment would be a big deal.

**Comment by rjruizes** [comment]
Quoting Evan from that thread:
> It's probably a mistake in how I added the "pretty" view. Like I've been saying to everyone about reactor, I needed to release without everything or I'd never get 0.17 out the door. Things will be fixed up later!
