### ISSUE TITLE
Time Travel Debugging not working anymore?

### ISSUE THREAD

**Issue by aravantv** [elm-lang/elm-reactor#186]
That's my first time using elm so maybe it's a stupid question... But how do we activate debugging?
I've read in the README that there should be a small "wrench" next to every file but I don't see any such thing...?

**Comment by doppioslash** [comment]
It's just a watcher at the moment, it check whenever you update something and compiles the code again.
The debugging features were removed to get 0.17 launched, at some point in the future the debugger functionality will be put back in afaik.

**Comment by aravantv** [comment]
What do you mean by watcher? For now I basically have to reload the page in my browser.
But I guess I'll just wait then, thanks for the (very) quick answer!

**Comment by doppioslash** [comment]
You have to reload it, but you don't have to compile it by hand using `elm-make`.
Cheers :)

**Comment by deathmood** [comment]
@doppioslash what so you mean by `The debugging features were removed to get 0.17 launched` ??
and when they'll get back?

**Comment by wjdhamilton** [comment]
👍

**Comment by maximsch2** [comment]
Should the README be updated then? It is really frustrating to spend time trying to fix "missing wrench" issue just to realize that it was removed in the new release.

**Comment by mariosangiorgio** [comment]
@deathmood for now you log the state to the Javascript console of your browser with [Debug.log](http://package.elm-lang.org/packages/elm-lang/core/4.0.1/Debug). It's not as nice as the time travel debugging but it allows you to check the state of your application.

**Comment by evancz** [comment]
Sorry for the confusion. It was not possible to fit all the upgrades into Elm 0.17 so these features will be coming back in a future release.

No one had features like this when it was introduced, so we did it kind of because we *could*. In practice it wasn't ready for a more serious workflow, so the plan is to do a redesign to get the features more in line with what users need in practice.

**Comment by absynce** [comment]
Has there been more discussion on this and #185? I'm trying to get an idea on where it's at in the scope of future releases. I just joined elm slack, so if I need to go to a channel there, that's fine too.
