### ISSUE TITLE
Bad visuals when error messages are too wide

### ISSUE THREAD

**Issue by neocris** [elm-lang/elm-reactor#188]
i noticed that for large pieces of code the spans in flex containers that include error notifications become too large and get out of view. i've seen spans with > 10k px wide. maybe adding a `max-width` rule will solve it although somehow i cannot get it working on firebug testing

**Comment by evancz** [comment]
Can you include a http://sscce.org/?

I am not sure how to reproduce this, and without that, I can't fix it!

**Comment by neocris** [comment]
sorry about that as i was a bit in a hurry. right now i can't remember the exact circumstances that lead to the event at the time because i eventually solved the bug and move on since. for now i will close this and if it turns up again i will reopen it with a more troughfully description
