### ISSUE TITLE
Link to elm-examples is a 404

### ISSUE THREAD

**Issue by brandondrew** [elm-lang/elm-reactor#192]
There is nothing at https://github.com/evancz/elm-examples

Perhaps you want to link to https://github.com/michaelbjames/elm-examples?  Or some other similar repo?

**Comment by eventualbuddha** [comment]
https://github.com/michaelbjames/elm-examples is based on an older version of Elm (0.13, it seems) and does not compile with the latest at time of writing (0.17?).

**Comment by evancz** [comment]
Thanks for pointing that out! I just switched it to https://github.com/evancz/elm-architecture-tutorial which parallels http://guide.elm-lang.org/
