### ISSUE TITLE
`elm reactor` is basically unusable on a crappy connection because of the external font

### ISSUE THREAD

**Issue by lydell** [elm-lang/elm-reactor#195]
I really like using `elm reactor`. It makes it so easy rapidly prototype things!

I also like coding on the train. There, the Internet connection ranges from okayish to awfully slow to none at all. It’s mostly in the “awfully slow” state.

So, what has the Internet connection on trains (in Sweden) to do with `elm reactor`? Basically, it boils down to this, which `elm reactor` includes in its served pages:

```css
@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro);
```

Nothing on the page renders before that request is done. So each time I refresh a page served by `elm reactor` I stare at a blank page for several minutes, only accompanied by this little tooltip in the browser’s bottom left corner:

![connecting-to-fonts](https://cloud.githubusercontent.com/assets/2142817/16143060/9f16e13c-346a-11e6-9141-262951951c98.png)

Usually, I just give up and run `elm make src/Main.elm && open index.html` instead.

Here are are a few alternatives:

- Get rid of the external font and create a really good font stack instead with the nicest, most common monospace system fonts.

- Load the font in a non-blocking way. Note that this might result in text being shown in a different font until the external font has loaded.

- Simply close this issue if nobody else has the same problem :) (I guess I could find a browser extension that blocks certain requests or something.)

**Comment by lydell** [comment]
@process-bot Here’s some extra info you asked for :)

OS: Ubuntu 16.04
Browser: Firefox Developer Edition 49.0a2
Elm: 0.17.0

Steps:

1. Run `elm reactor`.
2. Visit `http://localhost:8000` in a browser.
3. Click an .elm file on a crappy connection.

**Comment by evancz** [comment]
Thanks for the report, that's pretty lame! I did not know that `@import` worked like that. I can switch to using a `<link>` to load that info in and do it at the bottom of the page. There should be a 0.17.1 patch coming out relatively soon, so I'll make sure to get it in there!

**Comment by lydell** [comment]
Thanks for the update!

Your fix does seem to work on "directory listing" pages, but not on elm file pages:

```
$ elm reactor &
elm-reactor 0.17.1
Listening on http://localhost:8000/
$ curl -s http://localhost:8000/ | grep -o @import
$ curl -s http://localhost:8000/ | grep -o link
link
$ curl -s http://localhost:8000/src/Main.elm | grep link
$ curl -s http://localhost:8000/src/Main.elm | grep -o @import
@import
```

Note:

- `/`: `link` found, and not `@import`.
- `/src/Main.elm`: `link` _not_ found, but `@import` found instead.
