### ISSUE TITLE
[alpha] Two Errors in JavaScript console running simple program in Elm Reactor

### ISSUE THREAD

**Issue by clarkware** [elm-lang/elm-reactor#209]
I'm getting two errors in the JavaScript console when running a simple Hello World app in Elm Reactor using Elm 0.18.0.

OS: Mac OS X 10.11.6
Browser: Chrome Version 54.0.2840.71 (64-bit)

![screen shot 2016-10-25 at 10 30 17 am](https://cloud.githubusercontent.com/assets/4831/19694997/b4113ffc-9a9e-11e6-9b1d-fff9eb8fb798.png)

Also, I'm not seeing the result of Html.text being displayed in a simple "main" definition, whereas the text is displayed if I use "beginnerProgram". Here's a specific example. Given the following program, the HTML text "Hello!" is not being displayed in the browser:

```elm
module Main exposing (..)

import Html

main =
    Html.text "Hello!"
```

However, if I switch the program around to use a bare-bones "beginnerProgram" as follows, then the "Hello!" text is displayed in the browser as expected:

```elm
module Main exposing (..)

import Html

update msg model =
    model

view model =
    Html.text "Hello!"

main =
    Html.beginnerProgram
        { model = 0
        , view = view
        , update = update
        }
```

In both scenarios, the two JavaScript errors are shown in the error console.

**Comment by evancz** [comment]
Thanks for the report, should be fixed in the next alpha!

**Comment by clarkware** [comment]
Cool, thanks! Sorry, I looked around to see if it was a duplicate but didn't think to look in elm-make. Hopefully the multiple reports helped you triangulate.  :-)

**Comment by evancz** [comment]
It did, thanks!
