### ISSUE TITLE
Markdown files are enriched with HTML

### ISSUE THREAD

**Issue by fedragon** [elm-lang/elm-reactor#211]
Hi,
I am trying to serve Markdown files using `elm-reactor` and I see that they get enriched with HTML (see example below): is there any way to get the "raw" file, without any markup? I took a look at `Main.hs` but could not find anything.

Thank you in advance!

```
<!DOCTYPE HTML>
<html><head><meta charset="UTF-8"><title>~/slides.md</title><style type="text/css">@import url(http://fonts.googleapis.com/css?family=Source+Code+Pro);
html, head, body, pre {
  margin: 0;
  height: 100%;
}
body {
  font-family: 'Source Code Pro', monospace;
}
</style><link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/styles/default.min.css"><script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/highlight.min.js"></script><script>if (hljs) { hljs.initHighlightingOnLoad(); }</script></head><body style="background-color: #F0F0F0;"><pre><code># First slide

Lorem ipsum
</code></pre></body></html>
```

**Comment by evancz** [comment]
`elm-reactor` is not intended to be a proper server. It is nice for development, but when it comes to serving assets for real users, it isn't what you want anymore.

I think it makes sense to follow up with this line of questioning on elm-discuss or the Elm slack channel. If it seems like you have a case that warrants changing the behavior of `elm-reactor`, it makes sense to open a new issue that justifies why this change would benefit all users of `elm-reactor` and is worth it given the particular *goals* of `elm-reactor`.

**Comment by fedragon** [comment]
Hi @evancz, thank you for your reply, I understand your point of view. 
Just to clarify, my intent is not to use `elm-reactor` as a proper server: I am just developing a tool that parses markdown files and I was confused to get them enriched with markup. 

Thanks for mentioning `elm-discuss`, I will ask these kind of questions there from now on!
