### ISSUE TITLE
The new reactor truncates images

### ISSUE THREAD

**Issue by w0rm** [elm-lang/elm-reactor#213]
I've just migrated https://github.com/w0rm/elm-webgl-playground to 0.18, and the sprite was black because of the damaged image. I tried to open the image directly in the browser, this is what I got in Chrome:

![screen shot 2016-11-15 at 19 27 48](https://cloud.githubusercontent.com/assets/43472/20318417/7844c386-ab6a-11e6-9fb3-49f3b603760a.png)

**Comment by evancz** [comment]
You must get these down to http://sscce.org/ or there is nothing I can do. Please get it down to something that demonstrates the problem with elm-reactor as clearly as possible, then open a new issue explaining what you found.

**Comment by w0rm** [comment]
@evancz I can't tell more than this:

1. clone the repo `git clone git@github.com:w0rm/elm-webgl-playground.git`
2. run elm-reactor `cd elm-webgl-playground  && elm reactor`
3. open http://localhost:8000/textures/delivery-person.png in the browser to see what's in the screenshot. sometimes it even loads just the first row of animation frames

**Comment by w0rm** [comment]
The attachment below contains both images, the original, and the one dowloaded from the elm reactor:
[original-and-broken-image.zip](https://github.com/elm-lang/elm-reactor/files/592909/original-and-broken-image.zip)

**Comment by w0rm** [comment]
```
xxd delivery-person.png 1.hex
xxd delivery-person-broken.png 2.hex
vimdiff 1.hex 2.hex
```

Shows that the broken file (in the right tab) is served from the start:

![screen shot 2016-11-15 at 20 30 23](https://cloud.githubusercontent.com/assets/43472/20320662/ea04fdd0-ab72-11e6-88cd-a93dbe350166.png)

**Comment by evancz** [comment]
I understand that there is a big repo I can download. To create a good issue, you must make an http://sscce.org with everything stripped out except the core problem. You also need to say what OS you are on, what browser you are using, etc. Did you try it with other images? Other file extensions?

It seems like you are actively working towards getting an SSCCE in these comments, which is great. When you have it, open a new issue that explains it all in the first comment.

**Comment by w0rm** [comment]
@evancz thanks, I will try to get better at this!

**Comment by avh4** [comment]
@w0rm FYI, I did some investigation and created https://github.com/elm-lang/elm-reactor/issues/214

**Comment by w0rm** [comment]
@avh4 thanks! I was going to investigate, but didn't have time yesterday's evening.
