### ISSUE TITLE
Enable input ports

### ISSUE THREAD

**Issue by ThomasWeiser** [elm-lang/elm-reactor#36]
Assume we need a port for JS-interop, that sends values from JS to an Elm port.
The port needs to be declared to the function `Elm.fullscreen (module, ports)`.

To use the debugger of elm-reactor this function gets replaced by
`Elm.debugFullscreen (module, moduleFile, hotSwapState)`.
So we cannot declare any input port.

Evan [pointed out](https://groups.google.com/d/msg/elm-discuss/yXXC-_6wztw/ovfrODnRhgwJ) that it may be tricky while replaying old stuff. I guess, input ports should be handled the same way as builtin input like mouse or keyboard data. Output ports on the other hand should probably not send values out during replay.

**Comment by rehno-lindeque** [comment]
I'd like to bump this issue now that 0.15 is released - I find elm-reactor nearly indispensable for debugging. I've been dragging along https://github.com/elm-lang/elm-reactor/pull/63 through the upgrade to 0.14 because it was so useful to be able to supply some initial ports for debugging. However, it's pretty tricky to reapply it every time Elm upgrades. Would it be possible to look at this for the next release?

**Comment by vilterp** [comment]
Taking a look at this — seems like adding an argument to `fullscreenDebug` and saving the initial port values in the reactor's first snapshot shouldn't be too hard. Might not get to it for a couple weeks though.

**Comment by rehno-lindeque** [comment]
@vilterp I think it's going to look very similar to https://github.com/elm-lang/elm-reactor/pull/63 which was dead easy to do. Thanks for taking a look!

**Comment by thisredone** [comment]
:+1:

**Comment by danpalmer** [comment]
Is there any progress on this? I've just come to debug a trivial Elm application that I'm starting work on, but can't use this because it has ports, this seems like a pretty big limitation for any production application?

**Comment by evancz** [comment]
Future releases will be more focused on what production folks need. Can't have everything at once.

**Comment by flip111** [comment]
Could this be reconsidered? It's almost year ago and @danpalmer got quite a lot of upvotes. I would bet there are more people interested than the ones who upvoted, not everyone uses this github feature. I don't find it strange to want a quick feedback loop (with elm-reactor) and at the same time integrate elm with other javascript parts.
