### ISSUE TITLE
Reset button does not cause reset all of the fields 

### ISSUE THREAD

**Issue by Dandandan** [elm-lang/elm-reactor#41]
To reproduce:

* Go to http://debug.elm-lang.org/edit/Stamps.elm
* Add a few pentagons
* Click the reset/reload button
* Notice that "Stamps" still shows the old stamps
* Add a few pentagons and hit pause
* Go back in time and notice that the first stamp shows up in "Stamps" although it shouldn't.

**Comment by vilterp** [comment]
Restart button is broken right now (#122) so I can't verify that part, but filed separate issue for scrubbing to 0 not working (#123)
