### ISSUE TITLE
Non-ASCII characters in code prevent hotswapping

### ISSUE THREAD

**Issue by jastice** [elm-lang/elm-reactor#43]
Non-ASCII characters in code prevent hotswapping in the debugger.

* place any non-ASCII character anywhere in a source being watched by elm-reactor
* the code will not swap and throw an error in the JS console
* manually reloading does not show this problem

For example, save this as a utf-8 elm file, load it in the debugger and set it to hot-swap:

    main = asText "note"

Now, change a character to an umlaut:

    main = asText "nöte"

The debugger will not reload, and the javascript console throws an error: 

    Uncaught SyntaxError: Unexpected number

Remove the umlaut:

    main = asText "nute"

The code will reload fine.

**Comment by jastice** [comment]
Verified that issue persists in Elm Platform 0.14.1

**Comment by vilterp** [comment]
Closing as duplicate of #68, which has a more recent code example
