### ISSUE TITLE
"module.make is not a function" error when saving open file - hotswapping broken

### ISSUE THREAD

**Issue by fitzsnaggle** [elm-lang/elm-reactor#44]
module.make is not a function
Open the developer console for more details.

I'm getting this error using the elm-reactor whenever I save the file I'm working.
This was working previously and suddenly broke. Maybe there is a way a clear this error. I tried reinstalling and the error remained.

The program works fine when I reload the page.

**Comment by evancz** [comment]
This should be resolved with 0.14.1, so I am going to close for now. If you try [the alpha](https://groups.google.com/forum/#!topic/elm-discuss/KHg-aeFvDN0) and have the same error and no other issue is open that covers this, please reopen!
