### ISSUE TITLE
Type error output

### ISSUE THREAD

**Issue by toonn** [elm-lang/elm-reactor#48]
I think the expected and actual type errors are the wrong way round.
If I run the following code I get the errors in the attached image.
(Note that the actual error is a missing accumulator argument for the foldp in spaceCount.)

    -- Step 1: Change the below code so that it counts the number of user clicks.
    -- Step 2: Change the code so that it counts the number of user clicks
    --         and space bar presses.
    import Mouse
    import Keyboard
    
    clicks : Signal ()
    clicks = Mouse.clicks
    
    clickCount : Signal Int
    clickCount = foldp (\_ acc -> acc + 1) 0 clicks
    
    spaceCount : Signal Int
    -- spaceCount = countIf (identity) Keyboard.space
    spaceCount = foldp (\isdown acc -> if isdown then acc + 1 else acc)
                    Keyboard.space
    
    main : Signal Element
    main = lift2 above (lift asText clickCount) (lift asText spaceCount)

![elm_type_error](https://cloud.githubusercontent.com/assets/1486805/5089226/4b1be3c6-6f3a-11e4-893e-afcda7cc9e91.png)

(elm-reactor version 0.1, firefox version 33.0)

**Comment by evancz** [comment]
The expected/actual stuff is "resolved" with 0.14 and later by just stating the error a bit different. If things are still weird, open an issue on elm-compiler.
