### ISSUE TITLE
Module name may cause hot swapping to fail

### ISSUE THREAD

**Issue by jcollard** [elm-lang/elm-reactor#50]
Given the file `AnOkayModuleName.elm` with contents:

``` haskell
module AnOkayModuleName where
import Text (asText)
main = asText 42
```

If you run `elm-reactor` in the same directory as `AnOkayModuleName.elm` and debug it, hot swapping works fine. That is, you can change 42 to 45, save, and view the changes immediately.

However, changing the module name to `Test` and the file name to `Test.elm` causes hot swapping to fail. That is, it loads up fine but any change to the file (even without saving) causes the following error to be displayed in the browser:

```
Cannot use 'in' operator to search for 'recv' in undefined
    Open the developer console for more details.
```

I played around with it some more and the following file/module names also fail:

`Test2`, `TheTest`, `Two`, `Three`

It looks like anything that starts with a `T` will fail in the same way.

**Comment by evancz** [comment]
Okay, folks can check out the 0.14.1 alpha and see if it is fixed there: https://groups.google.com/forum/#!topic/elm-discuss/KHg-aeFvDN0

**Comment by eriksvedang** [comment]
Yes, it works. Yay and thanks!

**Comment by evancz** [comment]
Great, thank you for the confirmation!
