### ISSUE TITLE
0.14 - wrench link fails to load `debugging-runtime.js`

### ISSUE THREAD

**Issue by ghost** [elm-lang/elm-reactor#52]
### Context

I was following the [instructions on the `elm-reactor` readme](https://github.com/elm-lang/elm-reactor#time-travel-debugging) to utilize the time traveling debugger in elm 0.14. **[EDIT: Yes, it was installed on my Mac via the .pkg installer.]**
### Repro
1. run `elm-reactor` in my project dir
2. go to http://localhost:8000/ in my browser
3. click the small wrench next to an elm file

**Expected:** My elm program is started with a debugger/control panel
**Actual:** I get a blank white page. The javascript console contains the following errors (image attached) about not being able to load `debugging-runtime.js`

![screen shot 2014-12-04 at 10 01 29 am](https://cloud.githubusercontent.com/assets/1078772/5303256/915aba06-7b9c-11e4-8e70-e1096ba46a52.png)

**Comment by louisch** [comment]
I'm getting this error with 0.14 as well, on Arch Linux x86_64. I installed via cabal sandbox, using the script mentioned here: http://elm-lang.org/Install.elm#build-from-source

**Comment by evancz** [comment]
I have not released the fix yet, it should be in the next few days.
