### ISSUE TITLE
Automatically instantiate an elm module in the embedded scenario

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/elm-reactor#53]
The instructions for using reactor in the embedded scenario seem a little bit vague to me...

In particular,
```javascript
var runningElmModule = Elm.debugFullscreen(Elm.Todo, "todo.elm");
```
This code uses `Elm.Todo` even though `"todo.elm"` is also specified. However, I was expecting that the debugger itself would load the module (it is definitely great to work with the already instantiated module on top of an existing application though - which seems like it might be a goal if I'm reading the intent of this API correctly).

In any case, I think having the option to debug by simply passing a `null` module would be pretty helpful:
```javascript
var runningElmModule = Elm.debugFullscreen(null, "todo.elm");
```

It would also be nice to clarify in the README that `elm-reactor` should still run in the background in the embedded scenario in order to provide the hot-swapping functionality.

**Comment by evancz** [comment]
I'm going through the code to try to enable outgoing ports, so I'll try to make this less redundant as well. Seems plausible.

**Comment by evancz** [comment]
I'm not sure I understand what the intent was here. I think it makes sense to close and open a new issue if it makes sense to clarify things for the latest release.
