### ISSUE TITLE
Saving in debug mode cause error

### ISSUE THREAD

**Issue by eskimoblood** [elm-lang/elm-reactor#61]
When I run the debug mode and save the file I got the following error: 
```
Cannot use 'in' operator to search for 'recv' in undefined
```

The error happens in the `debugging-runtime.js` at line 51:

```
  if ( !('recv' in debuggedModule.main) ) {
    debuggedModule.main = Elm.Signal.make(runtime).constant(debuggedModule.main);
  }
```

cause `debuggedModule.main` is `undefined`

**Comment by evancz** [comment]
I believe this is fixed. Please try it out according to [these directions](https://groups.google.com/forum/#!topic/elm-discuss/KHg-aeFvDN0) and let me know the results!

**Comment by evancz** [comment]
Alright, this should be fixed. Please reopen if the issue persists with 0.14.1
