### ISSUE TITLE
Have to `rm -rf elm.js elm-stuff/` to reload correctly new .elm files.

### ISSUE THREAD

**Issue by yogsototh** [elm-lang/elm-reactor#62]
I am on Mac OS X Yosemite with the latest elm-platform downloaded from elm-lang.org.

If I don't delete the files, I continue to have exactly the same project as before.
For example switching from "Hello.elm" to another "Basic.elm" will continue to display the app of "Hello.elm".

But if I modify the "Basic.elm" file, then the content is updated.

**Comment by evancz** [comment]
This is an issue that has been noted at https://github.com/elm-lang/elm-make/issues/4 and https://github.com/elm-lang/elm-compiler/issues/844 so follow along with those to see the resolution of this one. elm-reactor is backed by elm-make, so the bug is at a lower level.
