### ISSUE TITLE
Hot swap is not working in debug mode

### ISSUE THREAD

**Issue by theburningmonk** [elm-lang/elm-reactor#65]
steps to repro:

this is the [file](https://gist.github.com/theburningmonk/c4826cbf5d96db5d23e3) used.
1. load in debug mode
2. change line 6 to `gameState = NotStarted`
3. save
4. observe error message:
```
Cannot use 'in' operator to search for 'recv' in undefined

Open the developer console for more details.
```

p.s. I'm running on Mac OSX

**Comment by louisch** [comment]
I am also getting this error on Arch Linux, elm-reactor 2.0.1.

It seems to happen even before I save the file in my case. As soon as I edit the file, the error happens.

Also, if I refresh the page (which fixes the error), and then save my unsaved changes, it produces the error again.

**Comment by evancz** [comment]
I have fixed this in the latest development version. I am working on a 0.14.1 release that includes the fix. That should be out in the next few days!
