### ISSUE TITLE
0.3 debugger - TypeError: Elm.fullscreenDebug is not a function

### ISSUE THREAD

**Issue by louisch** [elm-lang/elm-reactor#67]
Still getting this error in the Console, with a blank screen, while using the debugging feature (clicking the wrench next to the elm file) on 0.3:
```
TypeError: Elm.fullscreenDebug is not a function
```
Have tested on the examples in elm-examples, and the basic game skeleton.

Sorry if the fix isn't part of 0.3, I just assumed that it was.

Edit: seems the error is also happening with master

**Comment by evancz** [comment]
Have you upgraded to 0.14.1 such that all of your versions match [these](https://github.com/elm-lang/elm-platform/blob/master/src/BuildFromSource.hs#L60-L66)? Have you cleared out `elm-stuff/` to remove any build artifacts?

**Comment by louisch** [comment]
I used cabal sandbox to install a 0.14.1 in its own directory. I just double checked the git revisions of each repository inside, and it seemed each version matched.

As for `elm-stuff/`, I'm not sure which you're referring to, but I removed the one in `elm-examples`, and then removed one I found in `elm-reactor`, and retested it, and it still produced the same error.

Possibly unrelated, but the wrench symbol also seems to not be showing up. I'm getting what looks like a checkbox instead.

**Comment by evancz** [comment]
It sounds like you are missing the static resources needed for elm-reactor, so they may not be bundled correctly in general.

What platform are you on? (always put that in the issue!)

**Comment by louisch** [comment]
I see. I'm on Arch Linux x86_64.

When you say static resources, do you mean various haskell libraries?

**Comment by evancz** [comment]
I mean the stuff in [here](https://github.com/elm-lang/elm-reactor/tree/master/assets) which gets some extra generated files as well. All the files should be listed [here](https://github.com/elm-lang/elm-reactor/blob/master/elm-reactor.cabal#L33-L45) though I don't know what that maps to on your computer. If you are missing a favicon, the wrench, and `Elm.fullscreeDebug` is missing, I'm pretty sure it's about these resources.

My theory is that whatever is on hackage is missing these, but I'm not sure how to confirm or deny that.

**Comment by louisch** [comment]
I'll get back to you on this, but I suspect that cabal has been broken somehow on my system at this point, the `BuildFromSource.hs` script doesn't seem to even be generating the bin folder anymore.

**Comment by louisch** [comment]
OK, that's very odd. I deleted my .cabal folder to refresh my configuration (reinstalling cabal for good measure), and when I ran the build script again it generated the files in assets properly, and the debugger started working.

The only thing I can remember configuring was turning on library profiling in the configuration, but it was possible that messed up the configuration file, since cabal was reporting warnings about the configuration file.

I do know that I also moved the cabal sandbox after it was created, but I doubt that would have deleted files.

**Comment by evancz** [comment]
Ah, that's it. Moving the cabal sandbox messes stuff up. The binaries that are created point to an absolute location on disk, and when you move the sandbox, it moves the static resources. I've seen this once before, very tricky!

Sounds sorted out, so I am going to close. LMK if you run into anything else.

**Comment by valrus** [comment]
I am having this problem on Windows, with a fresh install of 0.14.1. I have haskell-platform installed as well but I don't think I've messed with anything cabal-related.

**Comment by evancz** [comment]
I think it was renamed to `Elm.debugFullscreen`, but I don't know enough about your case to help. Maybe open an issue with more information?

**Comment by alesguzik** [comment]
I have this problem with elm platform 0.15.1 installed from npm on archlinux x86_64. I'm quite new to elm, could you suggest where to look at?

**Comment by grandsong** [comment]
Here's how I workaround the (probably) same problem on my Windows 7 64x:

After I noticed that, in the file list page ("http://localhost:8000/"), **the icon before my 'App.elm' is broken**, I checked the "src" property of that <img>, which is _"/\_reactor/wrench.png"_. 

I had seen the file under **my elm platform folder**. So I simply **copy the "_reactor" folder to my project folder** and done!

I guess elm-reactor is supposed to silently use that shared folder (whoes path had alreay been set as "ELM_HOME" in my system Environment Variables correctly) for every project. However, it doesn't work.
