### ISSUE TITLE
Unicode character blocks hot-swap

### ISSUE THREAD

**Issue by jazmit** [elm-lang/elm-reactor#68]
The following compiles fine under elm-make and when browsing in reactor, but does not hot-swap on file write.

````elm
import Html (..)

main : Html
main = p [] [text "45°"]
````

Deleting the degree symbol and writing the file causes hotswap to resume without reloading the page.

**Comment by vilterp** [comment]
The JSON pushed to the browser on hot swap contains this:

```javascript
$Html.text(\"45\176\")
```
Inside a JSON string; parsing this with `python -m json.tool` gives us "Invalid \escape" at `\176`. 176 is the character code of the degree symbol (in decimal). If you use elm-make to compile straight to JS it gives `$Html.text("45°")`. Not sure where the improper escaping is occurring — maybe when we put the code into a JSON string on the server?
