### ISSUE TITLE
Hotswap blocks after compile error

### ISSUE THREAD

**Issue by jazmit** [elm-lang/elm-reactor#69]
If I write a file with a compile error, the error shows up in reactor, but any further changes require a page refresh to update reactor.

Eg: This program runs fine in reactor:
````elm
import Html (..)

main : Html
main = p [] [text "Hi"]
````

Changing the signature of main to `main : Signal` causes a compile error as expected.

````
Type mismatch between the following types on line 4, column 8 to 9:
        Html.Html
        Signal.Signal
````

But after changing the signature back to `main : Html`, the error persists until the page is refreshed.

**Comment by vilterp** [comment]
Can't reproduce this; I think it is fixed.
