### ISSUE TITLE
Invalid argument number in some notify calls?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-reactor#70]
Something fishy seems to be going on in that line:

https://github.com/elm-lang/elm-reactor/blob/master/frontend/debugger-implementation.js#L387

and in that line:

https://github.com/elm-lang/elm-reactor/blob/master/frontend/debugger-implementation.js#L443

In both lines, `notify` is called with three arguments. But all the `notify` functions that exist, be it from the "normal runtime" defined in `core`, or be it from `notifyWrapper`, have only two arguments.

Could it be that this is a remnant from a time when a third argument for the current timestamp was used, which got refactored away (but JavaScript not being strongly typed didn't notice that this should have led to a change in those two lines)?

**Comment by evancz** [comment]
I am guessing it was an optional argument to be used with the debugger, but I don't remember :/

In any case, looks like it's sorted out, thank you for opening this issue!
