### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by jastice** [elm-lang/elm-reactor#71]
elm-reactor still uses the old favicon (as of 0.3). Would be nice to update it to the one also used by the website (https://github.com/elm-lang/elm-lang.org/issues/208) or a variation thereof.

**Comment by evancz** [comment]
Want to do a PR to fix it?

**Comment by jastice** [comment]
Not today, maybe some day :)

**Comment by evancz** [comment]
Okay, should be fixed with d0a9cc94dde4074c2cf0bc8e98ce491f05a4956b so this will come out with the next version of Elm Platform. Thanks for opening the issue!
