### ISSUE TITLE
elm-reactor gives cryptic error when trying to debug a module without a public `main`

### ISSUE THREAD

**Issue by pchiusano** [elm-lang/elm-reactor#77]
```Elm
module Reactor (x) where -- notice `main` not exported

import Graphics.Element as Element
import Color

x : Int
x = 42

main = Element.spacer 10 10
    |> Element.color Color.red
```

Attempting to open this in debug view gives:

```
Cannot use 'in' operator to search for 'recv' in undefined

Open the developer console for more details.
```

Adding `main` to the export list `module Reactor (x, main) where ...` and it works as expected.

Maybe a better error message would be: "Could not open Elm debugger, since module does not export a `main` function" or some such?

**Comment by evancz** [comment]
Yeah, definitely! That's weird though because when you try to view a file with no `main` in other contexts, I believe it gives a reasonable message "Could not find `main` value, what do I display?`

**Comment by evancz** [comment]
Can open a new issue if this comes back in a future release.
