### ISSUE TITLE
Can't move the mario after hotswap

### ISSUE THREAD

**Issue by darthdeus** [elm-lang/elm-reactor#79]
To reproduce simply run `elm-reactor`, open the mario sample in the debug mode, edit the code (so that it hotswaps), switch back to the browser and see that you can't move the mario.

It starts working again after pausing & resuming in the debugger, though the game lags a lot after that.

**Comment by cocinerox** [comment]
Same here on Windows, v0.14.1. Also, the clock stops ticking.

**Comment by conklech** [comment]
Similar report here, although I'm not sure it's the same issue. Both Ubuntu+Firefox and Windows+Chrome produce the same behavior with `Mario.elm`:

Pressing the restart button (without changing the source file) makes Mario stop moving, etc. I can't get the simulation to restart by any pause/resume hijinks. The browser console shows this error:

    Uncaught Error: The notify function has been called synchronously!
    This can lead to frames being dropped.
    Definitely report this to <https://github.com/elm-lang/Elm/issues>
      notify                @ Mario.elm?debug:5497
      (anonymous function) @ debug.js:9097

**Comment by SeeThruHead** [comment]
if i change anything in an elm file the debugger stops working until a refresh, pausing and restarting the debugger don't do anything though.

**Comment by vilterp** [comment]
Filed three separate issues brought up here. There may be something additional going on.

- #127: module requires you to press pause, play after swap
- #126: strange things happen with timers after swap
- #122: runtime error when restart pressed

**Comment by evancz** [comment]
Can open a new issue if this persists in future releases.
