### ISSUE TITLE
request: hot-swap on save in normal view

### ISSUE THREAD

**Issue by johnjelinek** [elm-lang/elm-reactor#85]
Just like in `Inventing on Principle`, I want to be able to change values and immediately see how effects how my visualization changes.

**Comment by TheSeamau5** [comment]
I second this. I think plugging into something like `livereload` would be super cool.

**Comment by evancz** [comment]
What do you mean? If the "swap" button is on, you should just have to save the file. Is this not the case? Do you mean something different?

**Comment by TheSeamau5** [comment]
I think he means without going to the debugger

**Comment by johnjelinek** [comment]
Just like how figwheel works on Clojurescript apps. I hit save, renders change, state remains unchanged unless mutated (not reset to the beginning).

**Comment by evancz** [comment]
Tracking in #193, follow along there!
