### ISSUE TITLE
Debug.Watch and Debug.watchSummary point to 404s

### ISSUE THREAD

**Issue by eeue56** [elm-lang/elm-reactor#86]
When loading the debugger with no watches set, you get text telling you to set some.

Watch points to http://library.elm-lang.org/catalog/elm-lang-Elm/latest/Debug#watch

Watch summer points to http://library.elm-lang.org/catalog/elm-lang-Elm/latest/Debug#watchSummary

Neither of which exist any more. Perhaps there should be a single link to http://debug.elm-lang.org/ instead?

**Comment by evancz** [comment]
Fixed in recent release, thanks for the report!
