### ISSUE TITLE
Multiple browsers on elm-reactor

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-reactor#97]
So, I had an elm file open in Chrome served by elm-reactor. Then I tried opening it in firefox (the chrome one is still open). Then I noticed that firefox was taking forever. So, I closed the chrome one and as soon as I did that, firefox responded with this lovely message

```
A web handler threw an exception. Details:
thread killed
```

I'm guessing elm-reactor is meant to serve just one browser at a time? Am I correct?

**Comment by evancz** [comment]
Are you talking about doing debugging in two different browsers simultaneously? If so, it's not supported. That'd be a new feature, so let's close this one and start a thread specifically about that.

**Comment by TheSeamau5** [comment]
Follow up thread here: https://github.com/elm-lang/elm-reactor/issues/100
