### ISSUE TITLE
Failed with 'TypeDecodingFailed "time format invalid for TimeUTC : cannot convert string 0007181000Z"

### ISSUE THREAD

**Issue by romankras** [elm-lang/elm-reactor#98]
Hi, 

I am not able to launch any code from elm-reactor (I tried both [elm-examples](https://github.com/evancz/elm-examples) and my own code with/without errors). It's throwing the following error:

> failed with 'TypeDecodingFailed "time format invalid for TimeUTC : cannot convert string 0007181000Z"' when sending request to

Elm Reactor Details:
Elm Reactor 0.3.1 (Elm Platform 0.15)
Listening on http://0.0.0.0:8000/

My local enviorment details:
Windows 7 SP1 64-bit
Elm Platform 0.15

I suspect (but not 100% sure) that there could possibly be a bug in one of the underlying Haskell libraries since i've found couple of same issues:
https://github.com/snoyberg/http-client/issues/102
https://github.com/vincenthz/hs-certificate/issues/45
https://github.com/JPMoresmau/scion-class-browser/issues/18

Could somebody advice how to debug and create a patch for this? :)

**Comment by yogeshsajanikar** [comment]
Facing the same issue, while running elm examples

**Comment by yogeshsajanikar** [comment]
I found that System.X509.getSystemCertificateStore (Win32) throws this exception while decoding one of the certificate.

**Comment by evancz** [comment]
@romankras and @yogeshsajanikar, how did you install? Are you using the installer or building from source?

**Comment by romankras** [comment]
@evancz Elm Platform installer

**Comment by yogeshsajanikar** [comment]
@evancz I tried installation and building from source both. In both cases, I had same issue. I removed the certificate which was causing the error, and elm-package and elm-reactor could progress. Still facing a proxy related issue, but that is a different thing.

**Comment by jvoigtlaender** [comment]
@yogeshsajanikar, the issue you opened above in the probably responsible Haskell library has been fixed (according to their issue tracker). Are you able to check whether that does indeed solve the original problem here?

**Comment by yogeshsajanikar** [comment]
@jvoigtlaender, I checked that it was fixed sometime back.

**Comment by jvoigtlaender** [comment]
Cool, @yogeshsajanikar, thanks for this!

@romankras, I think this means you can close this issue here.
